server:
  port: 9999
  address: 0.0.0.0


spring:
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/utils?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tacbin@123
    driver-class-name: com.mysql.jdbc.Driver
